"""remove news model

Revision ID: 2555a49d58a3
Revises: 3bd61317e799
Create Date: 2015-01-05 21:45:34.574157

"""

# revision identifiers, used by Alembic.
revision = '2555a49d58a3'
down_revision = '3bd61317e799'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pystock_owner',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'pystock_book', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_column(u'pystock_book', 'user_id')
    op.alter_column(u'pystock_fxrates', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column(u'pystock_order', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_table('pystock_user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'pystock_order', 'owner_id')
    op.alter_column(u'pystock_fxrates', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column(u'pystock_book', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column(u'pystock_book', 'owner_id')
    op.drop_table('pystock_owner')
    ### end Alembic commands ###
