"""Added more models

Revision ID: 2c08fb5b6e72
Revises: 3bfca079f84d
Create Date: 2014-09-01 00:01:51.077215

"""

# revision identifiers, used by Alembic.
revision = '2c08fb5b6e72'
down_revision = '4ee9a9c23b8f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.add_column(u'pystock_fxrates', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column(u'pystock_fxrates', sa.Column('created_on', sa.DateTime(), nullable=False))

    op.create_table('pystock_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pystock_book',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['pystock_user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('pystock_trade',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_on', sa.DateTime(), nullable=False),
        sa.Column('trade_date', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('broker_id', sa.Integer(), nullable=True),
        sa.Column('amount', sa.DECIMAL(), nullable=True),
        sa.Column('price', sa.DECIMAL(), nullable=True),
        sa.Column('operation_code', sa.String(), nullable=False),
        sa.Column('trade_type', sa.String(), nullable=False),

        sa.ForeignKeyConstraint(['user_id'], ['pystock_user.id'], ),
        sa.ForeignKeyConstraint(['broker_id'], ['pystock_broker.id'], ),
        sa.PrimaryKeyConstraint('id')

    )

    op.create_table('pystock_exchange',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('code', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'pystock_exchange', ['code'])

    op.add_column(u'pystock_security', sa.Column('exchange_id', sa.Integer(), nullable=False))
    op.create_foreign_key("pystock_security_exchange_id_fkey", "pystock_security", "pytstock_exchange", ["exchange_id"], ["id"])

    op.create_table('pystock_liability',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pystock_company',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # ## end Alembic commands ###


def downgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pystock_currency')
    op.drop_column(u'pystock_fxrates', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column(u'pystock_fxrates', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.drop_table('pystock_book')
    op.drop_table('pystock_user')
    op.drop_table('pystock_trade')
    op.drop_table('pystock_exchange')
    op.drop_table('pystock_liability')
    op.drop_table('pystock_company')
    # ## end Alembic commands ###
