"""empty message

Revision ID: 7d0cfaec4a0
Revises: None
Create Date: 2014-08-03 22:17:13.049919

"""

# revision identifiers, used by Alembic.
revision = '7d0cfaec4a0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.add_column(u'pystock_broker', sa.Column('address', sa.String(), nullable=True))
    op.add_column(u'pystock_broker', sa.Column('phone', sa.String(), nullable=True))
    # ## end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'pystock_broker', 'phone')
    op.drop_column(u'pystock_broker', 'address')
    ### end Alembic commands ###
